# -*- coding: utf-8 -*-
"""
Created on Tue Oct 27 06:34:30 2015

@author: Alex
"""

#old text


document.add_paragraph("A land cover map (2.5 m resolution) (NOAA Ocean Service and Coastal Services Center, 2010) classified the predominant land cover in Faga'alu watershed as undisturbed ("+"%.1f"%landcover_table.ix[5]['% Undisturbed']+"%), including forest ("+"%.1f"%landcover_table.ix[5]['% Forest']+"%) and scrub/shrub ("+"%.1f"%landcover_table.ix[5]['% Scrub/ Shrub']+"%) on the steep hillsides (Table "+landcover_table.table_num+"), where natural landsliding can contribute large amounts of sediment during storm events (Buchanan-Banks, 1979; Calhoun and Fletcher, 1999). Compared to other watersheds on Tutuila, a relatively large portion of Faga'alu watershed is urbanized ("+"%.1f"%landcover_table.ix[5]['% High Intensity Developed']+"% "+'"High Intensity Developed"'+" in Table "+landcover_table.table_num+"), due to large areas of impervious surface associated with the hospital and the numerous residences and businesses. A small portion of the watershed ("+"%.1f"%landcover_table.ix[5]['% Developed Open Space']+"%) is developed open space, which includes landscaped lawns and parks. In addition to some small household gardens there are several small agricultural areas growing banana and taro on the steep hillsides. These agricultural plots were classified as "+'"Grassland"'+" due to the high fractional grass cover in the plots. Farmers of these plots are currently receiving technical assistance from the Natural Resource Conservation Service (NRCS) to mitigate erosion. There are several small footpaths and unpaved driveways in the village, but most unpaved roads are stabilized with compacted gravel and do not appear to be a major contributor of sediment (Horsley-Witten, 2012b). Longitudinal sampling of Faga'alu stream during baseflow conditions in 2011 showed significantly increased turbidity downstream of a bridge construction site on the village road approximately 200 m downstream of FG2 (Curtis et al., 2011). Construction of the bridge was completed in March 2012 and no longer increases turbidity.")

document.add_paragraph("An open-pit aggregate quarry, covering 1.6 ha ("+"%.1f"%landcover_table.ix[1]['% Bare Land']+"% of LOWER_QUARRY subwatershed) accounts for the majority of the "+"%.1f"%landcover_table.ix[5]['% Bare Land']+"% Bare Land in Faga'alu watershed (Table "+landcover_table.table_num+"). The quarry has been in continuous operation since the 1960's by advancing into the steep hillside to quarry the underlying basalt formation (Latinis 1996). The overburden soil and weathered rock was either piled up on-site where it was eroded by storms, or was manually rinsed from crushed aggregate. With few sediment runoff controls in place, the sediment was discharged directly to the stream. In 2011, the quarry operators installed some sediment runoff management practices such as silt fences and settling ponds (Horsley-Witten, 2011) but they were unmaintained and inadequate to control the large amount of sediment mobilized during storm events (Horsley-Witten, 2012a). In 2013, additional control structures were installed to route the groundwater seep directly from the blast face into the stream, to prevent it from eroding sediment from the haul road into the stream. Crushed rock was also distributed over the haul road and landings to decrease erodible sediment, and some large piles of overburden were naturally overgrown by vegetation (Figure "+Quarry_picture['fig_num']+")(See Holst-Rice et al. (in press) for a full description of mitigation efforts at the quarry).")


document.add_paragraph("At FG3, the channel is rectangular with stabilized rip-rap banks and bed (Appendix Figure "+LBJ_Cross_Section['fig_num']+"). Recorded stage varied from "+"%.0f"%LBJ['stage'].min()+" to "+"%.0f"%LBJ['stage'].max()+" cm. Area-velocity Q measurements (n= "+"%.0f"%len(LBJstageDischarge)+") were made from "+"%.0f"%LBJstageDischarge['Q-AV(L/sec)'].min()+" to "+"{:,}".format(LBJstageDischarge['Q-AV(L/sec)'].max())+" L/sec, covering a range of stages from "+"%.0f"%LBJstageDischarge['stage(cm)'].min()+" to "+"%.0f"%LBJstageDischarge['stage(cm)'].max()+" cm. The highest recorded stage was much higher than the highest stage with measured Q so the rating could not be extrapolated by a power law. Stream conditions at FG3 fit the assumption for Manning's equation, so the stage-Q rating at FG3 was created using Manning's equation, calibrating Manning's n (0.067) to the Q measurements (Figure "+LBJ_StageDischarge['fig_num']+").") 




document.add_paragraph("Using the stage threshold method and manual separation of complex storm events, valid Q data was recorded during "+"%.0f"%No_of_Storm_Intervals_DAM_Q+" events at FG1, and "+"%.0f"%No_of_Storm_Intervals_LBJ_Q+" events at FG3 from January, 2012, to July 2014 (Appendix 3, Table "+Q_Diff_table.table_num+"). Valid SSC data from T or interpolated grab samples was recorded during "+"%.0f"%No_of_Storm_Intervals_DAM_S+" events at FG1, and "+"%.0f"%No_of_Storm_Intervals_LBJ_S+" events at FG3. Of those storms, "+"%.0f"%S_Diff_table['Storm#'][S_Diff_table['Storm#']!=''].astype(float).max()+" events had valid P, Q, and SSC data for both the FG1 and FG3 to calculate and compare SSY from the UPPER and LOWER subwatersheds. Valid SSY data from interpolated grab samples was collected at FG2 for "+No_of_Storm_Intervals_QUA_S+" storms to compare with SSY from FG1 and FG3. Storm event durations ranged from "+"%.0f"%LBJ_StormIntervals['duration (hrs)'].min()+" hours to "+"%.0f"%max_storm_duration+" days, with mean duration of "+"%.0f"%LBJ_StormIntervals['duration (hrs)'].mean()+" hours.") 



document.add_paragraph("Using the measured sSSY from the forested UPPER watershed (="+sSSY_UPPER_2+" tons/km2), SSY from the undisturbed forest areas in the LOWER watershed was "+SSY_disturbed_table['LOWER']['SSY from forested areas (tons)']+" tons, and SSY from the disturbed areas was "+SSY_disturbed_table['LOWER']['SSY from disturbed areas (tons)']+" tons. For the measured storms (Table "+SSY_disturbed_table.table_num+"), roughly "+SSY_disturbed_table['LOWER']['% SSY from disturbed areas']+"% of SSY from the LOWER subwatershed was from disturbed areas, despite the disturbed areas only accounting for "+SSY_disturbed_table['LOWER']['fraction disturbed (%)']+"% of the LOWER subwatershed area ("+"%0.3f"%disturbed_area_LOWER+" km2). Similarly, despite only "+SSY_disturbed_table['TOTAL']['fraction disturbed (%)']+"% of the TOTAL watershed being disturbed, SSY from disturbed areas accounted for "+SSY_disturbed_table['TOTAL']['% SSY from disturbed areas']+"% of the SSY from the TOTAL watershed. Estimated sSSY from disturbed areas in the LOWER subwatershed was "+"{:,g}".format(float(SSY_disturbed_table['LOWER']['sSSY from disturbed areas (tons/km2)']))+" tons/km2, suggesting human disturbance has increased sSSY by "+SSY_disturbed_table['LOWER']['DR for sSSY from disturbed areas']+"x over undisturbed, forest conditions.")


document.add_paragraph("SSY for the "+No_of_Storm_Intervals_QUA_S+" storms at FG3 was "+SSY_TOTAL_3+" tons wtih an average of "+Percent_UPPER_S_3+"% from the UPPER subwatershed, "+Percent_QUARRY_S+"% from LOWER_QUARRY subwatershed, and "+Percent_VILLAGE_S+"% from the LOWER_VILLAGE subwatershed (Table "+S_Diff_table_quarry.table_num+"). sSSY from the UPPER, LOWER_QUARRY, and LOWER_VILLAGE subwatersheds, and the TOTAL watershed was "+sSSY_UPPER_3+", "+sSSY_LOWER_QUARRY+", "+sSSY_LOWER_VILLAGE+", and "+sSSY_TOTAL_3+" tons/km2, respectively. sSSY from LOWER_QUARRY and LOWER_VILLAGE was "+S_Diff_table_quarry['LOWER_QUARRY tons']['DR']+" and "+S_Diff_table_quarry['LOWER_VILLAGE tons']['DR']+" times higher, respectively, than sSSY from UPPER subwatershed, suggesting human disturbance has significantly increased SSY over natural levels, particularly at the quarry. sSSY from the TOTAL watershed was "+S_Diff_table_quarry['TOTAL tons']['DR']+" times higher than the UPPER subwatershed, similar to the larger range of storms in Table "+S_Diff_table.table_num+", where sSSY was "+S_Diff_table['TOTAL tons']['DR']+" times higher than forested conditions.")

if 'SSY_disturbed_table_quarry' in locals():
    dataframe_to_table(df=SSY_disturbed_table_quarry,table_num=SSY_disturbed_table_quarry.table_num,caption="Sediment yield from disturbed portions of UPPER, LOWER_QUARRY and LOWER_VILLAGE subwatersheds in Faga'alu.",fontsize=9)
    
    
    


document.add_paragraph("Bare land in the LOWER_QUARRY subwatershed significantly increased sSSY, and contributed the majority of SSY from disturbed areas in Faga'alu watershed. Human disturbance in the LOWER_VILLAGE subwatershed also increased SSY above natural levels but the magnitude of disturbance was much lower than the quarry. SSY from undisturbed areas in the LOWER_QUARRY and LOWER_VILLAGE subwatersheds was: "+SSY_disturbed_table_quarry['LOWER_QUARRY']['SSY from forested areas (tons)']+" and "+SSY_disturbed_table_quarry['LOWER_VILLAGE']['SSY from forested areas (tons)']+" tons, respectively (Table "+SSY_disturbed_table_quarry.table_num+"). SSY from the "+"%0.3f"%disturbed_area_LOWER_QUARRY+" km2 and "+"%0.3f"%disturbed_area_LOWER_VILLAGE+" km2 of disturbed areas in the LOWER_QUARRY and LOWER_VILLAGE subwatersheds was "+SSY_disturbed_table_quarry['LOWER_QUARRY']['SSY from disturbed areas (tons)']+" and "+SSY_disturbed_table_quarry['LOWER_VILLAGE']['SSY from disturbed areas (tons)']+" tons, respectively. SSY from the disturbed areas accounted for "+SSY_disturbed_table_quarry['LOWER_QUARRY']['% SSY from disturbed areas']+"% and "+SSY_disturbed_table_quarry['LOWER_VILLAGE']['% SSY from disturbed areas']+"% of total SSY from those subwatersheds, respectively. sSSY from disturbed areas in the UPPER, LOWER_QUARRY, and LOWER_VILLAGE subwatersheds was "+SSY_disturbed_table_quarry['UPPER']['sSSY from disturbed areas (tons/km2)']+", "+"{:,g}".format(float(SSY_disturbed_table_quarry['LOWER_QUARRY']['sSSY from disturbed areas (tons/km2)']))+", and "+SSY_disturbed_table_quarry['LOWER_VILLAGE']['sSSY from disturbed areas (tons/km2)']+" tons/km2, respectively, suggesting that disturbed areas increase sSSY over forested conditions by "+SSY_disturbed_table_quarry['LOWER_QUARRY']['DR for sSSY from disturbed areas']+"x and "+SSY_disturbed_table_quarry['LOWER_VILLAGE']['DR for sSSY from disturbed areas']+"x in the LOWER_QUARRY and LOWER_VILLAGE subwatersheds, respectively.")

document.add_paragraph("A very small fraction of the watershed accounted for the majority of the sediment yield from the watershed. Roughly "+SSY_disturbed_table_quarry['LOWER_QUARRY']['% SSY from disturbed areas']+"% and "+SSY_disturbed_table_quarry['LOWER_VILLAGE']['% SSY from disturbed areas']+"% of SSY from the LOWER_QUARRY and LOWER_VILLAGE subwatersheds, respectively, was from disturbed areas, despite the disturbed areas only accounting for "+SSY_disturbed_table_quarry['LOWER_QUARRY']['fraction disturbed (%)']+"% and "+SSY_disturbed_table_quarry['LOWER_VILLAGE']['fraction disturbed (%)']+"% of the subwatershed area, respectively. Similarly, despite only "+SSY_disturbed_table_quarry['TOTAL']['fraction disturbed (%)']+"% of the TOTAL watershed being disturbed, SSY from disturbed areas accounted for "+SSY_disturbed_table_quarry.ix['% SSY from disturbed areas']['TOTAL']+"% of the SSY from the TOTAL watershed for the 8 storms, and 74% for the 24 storms (Table "+SSY_disturbed_table_quarry.table_num+").")


document.add_paragraph("SSYEV from the UPPER and TOTAL watersheds correlated with each of the four storm metrics tested (Figure "+SSY_models_ALL['fig_num']+"). Significant scatter was observed for all models, which reflects the changing sediment availability at the quarry and village, and the natural variability in the watershed response for different storm events. In general, SSYEV and precipitation metrics (Psum and EI30) showed lower Pearson and Spearman correlation coefficients compared to the discharge metrics (Qsum and Qmax)(Table "++"). Pearson and Spearman correlation coefficients were fairly similar, meaning the relationships were mostly linear in log-log space. The exception was Qmax for the UPPER subwatershed (Pearson's: "+"%.2f"%QmaxS_upper_power.pearson+" vs. Spearman's: "+"%.2f"%QmaxS_upper.spearman+"). Only EI30 had a higher Pearson's correlation coefficient than Spearman's, but both were low compared to the other storm metrics (Pearson's: "+"%.2f"%EI_total.pearson+" vs. Spearman's: "+"%.2f"%EI_total.spearman+").")


document.add_paragraph("ANCOVA was used to compare regression coefficients (Beta=slope and alpha=intercept)  of the UPPER and TOTAL SSY models, to determine if the percentage sediment contribution from human-disturbed areas changed with storm size. All model intercepts were significantly different (p<0.05), but only the Psum-SSYEV model showed significantly different (p<0.05) slopes. It was hypothesized that for large storms, SSYEV from the UPPER watershed may become relatively more important for total SSY to Faga'alu Bay, however, the models show conflicting results. The Psum-SSYEV models indicate that for larger storm events SSY from the UPPER and TOTAL watersheds are more similar, as the regression lines converge at higher Psum values. Conversely, the Qsum- and Qmax-SSYEV models show no change in relative contributions of SSY over the range of storm sizes (Figure "+SSY_models_ALL['fig_num']+"). In that case, the discharge models (Qsum and Qmax) support the conclusion that human disturbance does not diminish with storm size, while the Psum model supports the conclusion that human-disturbance does diminsh with storm size.")


#document.add_paragraph("SSY from the UPPER, LOWER, and TOTAL watersheds was "+SSY_UPPER_2+", "+SSY_LOWER_2+", and "+SSY_TOTAL_2+" tons, respectively. sSSY from the UPPER, LOWER, and TOTAL watersheds was "+sSSY_UPPER_2+", "+sSSY_LOWER_2+", and "+sSSY_TOTAL_2+" tons/km2, respectively.")

#document.add_paragraph("For the storms totaling "+P_measured_3+" mm of precipitation measured in , SSY from the UPPER, LOWER_QUARRY, and LOWER_VILLAGE subwatersheds was "+SSY_UPPER_3+", "+SSY_LOWER_QUARRY+", and "+SSY_LOWER_VILLAGE+" tons, respectively, and sSSY from the UPPER, LOWER_QUARRY, and LOWER_VILLAGE subwatersheds was "+sSSY_UPPER_3+", "+sSSY_LOWER_QUARRY+", and "+sSSY_LOWER_VILLAGE+" tons/km2, respectively. SSY and sSSY from the TOTAL watershed was "+SSY_TOTAL_3+" tons and "+sSSY_TOTAL_3+" tons/km2, respectively.")
#("+LOWER_QUARRY_disturbed_fraction+"%) 
#("+"%0.2f"%Area_LOWER_QUARRY+" km2)







